apps/plans/urls.py
from django.urls import re_path, path
from plans.views import ProcessListView, CreatePlanView, EditPlanView, CreateProcessView

app_name = 'plans'

urlpatterns = [
    re_path(r'^plan/(?P<plan_id>[0-9]+)/', ProcessListView.as_view(), name='process'),
    re_path(r'^createplan/', CreatePlanView.as_view(), name='create_plan'),
    re_path(r'^editplan/(?P<plan_id>[0-9]+)\d+/', EditPlanView.as_view(), name='edit_plan'),
    re_path(r'^createprocess/(?P<pk>[0-9]+)/', CreateProcessView.as_view(), name='create_process'),
]

apps/task/urls.py
from django.urls import re_path
from task.views import MakeTaskView, ListTaskView

app_name = 'task'

urlpatterns = [
	re_path(r'^send_parameter/', MakeTaskView.as_view(), name='send_parameter'),
	re_path(r'^list_task/', ListTaskView.as_view(), name='list_task')
]

lifestation/urls.py
from django.urls import path, re_path, include
import xadmin
from users.views import LoginView, RegisterView, IndexView, ActiveUserView, LogoutView
from lifestation import corn
from .settings import DEBUG

if not DEBUG:
    corn.main()
urlpatterns = [
    path('admin/', xadmin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(),name='user_active'),
    path("users/", include('users.urls', namespace="users")),
    # plans url
    path("plans/", include('plans.urls', namespace="plans")),

	path("task/",include('task.urls',namespace="task")),

]

apps/plans/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Plans(models.Model):

    goal = models.CharField(max_length=70, default='money')

    now_status = models.CharField(max_length=2000,default='no money')
    future_status = models.CharField(max_length=2000, default='a lot of money')
    mtime = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    ctime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    count = models.IntegerField(verbose_name='倒计时', default=0)
    author = models.ForeignKey(User, related_name='goal', on_delete=models.CASCADE)
    is_delete = models.BooleanField(verbose_name='是否已删除', default=False)
    is_complete = models.BooleanField(verbose_name='是否已实现', default=False)

    class Meta:
        ordering = ['-mtime', '-ctime']
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.goal


class Process(models.Model):

    process_name = models.CharField(max_length=70)
    mtime = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    ctime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    plan_id = models.ForeignKey(Plans, related_name='process', on_delete=models.CASCADE)

    TIME_CHOICES = (
        ('long_time', '长期执行'),
        ('period_time', '阶段执行')
    )

    time_choice = models.CharField(verbose_name='任务时间属性', max_length=20, choices=TIME_CHOICES, default='long_time')
    start_time = models.DateTimeField(verbose_name='开始日期')
    end_time = models.DateTimeField(verbose_name='结束日期')

    content = models.CharField(verbose_name='方法', max_length=2000)
    is_delete = models.BooleanField(verbose_name='是否已删除', default=False)
    is_complete = models.BooleanField(verbose_name='是否已实现', default=False)


class ProcessScore(models.Model):
    STATUS_CHOICES = (
        ('complete', '完成'),
        ('do', '执行'),
        ('try', '尝试'),
        ('forget', '遗忘')
    )

    process_status = models.CharField(verbose_name='任务时间属性', max_length=8, choices=STATUS_CHOICES, default='forget')
    process_score = models.IntegerField(verbose_name='分数', default=0)
    process_id = models.ForeignKey(Process, related_name='score', on_delete=models.CASCADE)

apps/task/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()


class Task(models.Model):

	user = models.ForeignKey(User, related_name='ZUOZHE', on_delete=models.CASCADE)
	name = models.CharField('任务', max_length=200, default='1')
	mtime = models.DateTimeField(verbose_name='修改时间', auto_now=True)
	ctime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

	key_word = models.CharField('关键词', max_length=200, default='')
	target_web = models.CharField('目标网址', max_length=100, default='')

	run_day = models.IntegerField('持续天数', default=0)
	run_time = models.IntegerField('目标次数', default=0)

	count_time = models.IntegerField('统计次数', default=0)
	count = models.IntegerField('统计使用次数', default=0)

	STATUS_CHOICE = (
		(0, "未开始"),
		(1, "开始任务"),
		(2, "暂停任务"),
		(3, "完成"),
	)
	status = models.CharField('状态', choices=STATUS_CHOICE, max_length=50, default=0)

	STATUS_URL = (
		('百度', "https://www.baidu.com"),
		('谷歌', "https://www.baidu.com"),
		('搜狗', "https://www.baidu.com"),
		('360', "https://www.baidu.com"),
	)
	search_url = models.CharField('搜索引擎', max_length=100, default='百度')

apps/task/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from task.models import Task

# Create your views here.

class MakeTaskView(View):

	def get(self, request):
		return redirect('index')

	def post(self, request):
		try:
			task = Task()

			return redirect('index')

		except Exception as e:
			print(1111)



class ListTaskView(View):
	def get(self, request):
		task_list = Task.objects.all()
		return render(request, "task.html",
                {'task_list': task_list})

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{% block title %}zhang_derek首页{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'process/assets/css/main.css'%}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->


	</head>
	<body class="single">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="{% url 'index' %}">Future Imperfect</a></h1>
						<nav class="links">
							<ul>
								<li><a href="{% url 'plans:create_plan' %}">new</a></li>
								<li><a href="#">Ipsum</a></li>
								<li><a href="#">Feugiat</a></li>
								<li><a href="#">Tempus</a></li>
								<li><a href="{% url 'logout' %}">LogOut</a></li>
							</ul>
						</nav>
						<nav class="main">
							<ul>
								<li class="search">
									<a class="fa-search" href="#search">Search</a>
									<form id="search" method="get" action="#">
										<input type="text" name="query" placeholder="Search" />
									</form>
								</li>
								<li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Menu -->
					<section id="menu">

						<!-- Search -->
							<section>
								<form class="search" method="get" action="#">
									<input type="text" name="query" placeholder="Search" />
								</form>
							</section>

						<!-- Links -->
							<section>
								<ul class="links">
									<li>
										<a href="#">
											<h3>Lorem ipsum</h3>
											<p>Feugiat tempus veroeros dolor</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Dolor sit amet</h3>
											<p>Sed vitae justo condimentum</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Feugiat veroeros</h3>
											<p>Phasellus sed ultricies mi congue</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Etiam sed consequat</h3>
											<p>Porta lectus amet ultricies</p>
										</a>
									</li>
								</ul>
							</section>

						<!-- Actions -->
							<section>
								<ul class="actions vertical">
									<li><a href="#" class="button big fit">Log In</a></li>
								</ul>
							</section>

					</section>

				{% block content %}

                {% endblock %}

		<!-- Scripts -->
			<script src="{% static 'process/assets/js/jquery.min.js'%}"></script>
			<script src="{% static 'process/assets/js/skel.min.js'%}"></script>
			<script src="{% static 'process/assets/js/util.js'%}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'process/assets/js/main.js'%}"></script>

            </div>>
    </body>
</html>

templates/create_plan.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Single - Future Imperfect by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'process/assets/css/main.css'%}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body class="single">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="{% url 'index' %}">Future Imperfect</a></h1>
						<nav class="links">
							<ul>
								<li><a href="{% url 'plans:create_plan' %}">new</a></li>
								<li><a href="#">Ipsum</a></li>
								<li><a href="#">Feugiat</a></li>
								<li><a href="#">Tempus</a></li>
								<li><a href="{% url 'logout' %}">LogOut</a></li>
							</ul>
						</nav>
						<nav class="main">
							<ul>
								<li class="search">
									<a class="fa-search" href="#search">Search</a>
									<form id="search" method="get" action="#">
										<input type="text" name="query" placeholder="Search" />
									</form>
								</li>
								<li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Menu -->
					<section id="menu">

						<!-- Search -->
							<section>
								<form class="search" method="get" action="#">
									<input type="text" name="query" placeholder="Search" />
								</form>
							</section>

						<!-- Links -->
							<section>
								<ul class="links">
									<li>
										<a href="#">
											<h3>Lorem ipsum</h3>
											<p>Feugiat tempus veroeros dolor</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Dolor sit amet</h3>
											<p>Sed vitae justo condimentum</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Feugiat veroeros</h3>
											<p>Phasellus sed ultricies mi congue</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Etiam sed consequat</h3>
											<p>Porta lectus amet ultricies</p>
										</a>
									</li>
								</ul>
							</section>

						<!-- Actions -->
							<section>
								<ul class="actions vertical">
									<li><a href="#" class="button big fit">Log In</a></li>
								</ul>
							</section>

					</section>

				<!-- Main -->
					<div id="main">
                        {% if plan %}
                            <div class="other_login">
                                <button  type="submit" >COMPLETE</button>
                                <button style="float: right" type="submit" onclick="window.location.href='{% url 'plans:create_process' plan.id %}'" >DELETE</button>
							</div>
                            <form action="{% url 'plans:edit_plan' plan.id %}" method="post">

							<div class="search">
                                <textarea name="goal" style="width:100%;height:50px;margin-top: 10px">{{ plan.goal }}</textarea>
							</div>

							<div class="form_text_ipt">
								<textarea name="now_status" id="now_status" style="width:100%;height:100px;margin-top: 10px">{{ plan.now_status }}</textarea>
							</div>

							<div class="form_text_ipt">
                                <textarea name="future_status" id="future_status" style="width:100%;height:100px;margin-top: 10px" placeholder="未来">{{ plan.future_status }}</textarea>
							</div>

                            <div class="form_text_ipt">
								<br>
							</div>

                            <div class="form_text_ipt">
								<ul>
								<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;开始：<input name="start_date" id="start" type="date" placeholder="开始">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;结束：<input name="end_date" id="future_status" type="date" placeholder="结束"></li>
							    </ul>
							</div>


{#							<div class="form_text_ipt">#}
{#								<input name="code" type="text" placeholder="验证码">#}
{#							</div>#}
{#							<div class="ececk_warning"><span>验证码不能为空</span></div>#}

							<div class="other_login">
                                <button  type="submit" >UNDO</button>
                                <button style="float: right" type="submit" >START</button>
							</div>


                            <div class="error btns login-form-tips" id="jsLoginTips">
                                {% for key,error in register_form.errors.items %}
                                    {{ error }}
                                {% endfor %}
                                {{ msg }}
                            </div>
                            <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                                {% csrf_token %}


						</form>
                        {% else %}

                            <form action="{% url 'plans:create_plan' %}" method="post">

							<div class="search">
								<input name="goal" type="text" id="goal" placeholder="目标">
							</div>

							<div class="form_text_ipt">
								<textarea name="now_status" id="now_status" style="width:100%;height:100px;margin-top: 10px" placeholder="现状"></textarea>
							</div>

							<div class="form_text_ipt">
                                <textarea name="future_status" id="future_status" style="width:100%;height:100px;margin-top: 10px" placeholder="未来"></textarea>
							</div>

                            <div class="form_text_ipt">
								<br>
							</div>

                            <div class="form_text_ipt">
								<ul>
								<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;开始：<input name="start_date" id="start" type="date" placeholder="开始">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;结束：<input name="end_date" id="future_status" type="date" placeholder="结束"></li>
							    </ul>
							</div>


{#							<div class="form_text_ipt">#}
{#								<input name="code" type="text" placeholder="验证码">#}
{#							</div>#}
{#							<div class="ececk_warning"><span>验证码不能为空</span></div>#}

							<div class="other_login">

                                <button  type="submit" >START</button>

							</div>

                            <div class="error btns login-form-tips" id="jsLoginTips">
                                {% for key,error in register_form.errors.items %}
                                    {{ error }}
                                {% endfor %}
                                {{ msg }}
                            </div>
                            <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                                {% csrf_token %}


						</form>
                    {% endif %}
                </div>


				<!-- Footer -->
					<section id="footer">
{#						<ul class="icons">#}
{#							<li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>#}
{#							<li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>#}
{#							<li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>#}
{#							<li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>#}
{#							<li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>#}
{#						</ul>#}
						<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
					</section>

			</div>

		<!-- Scripts -->
			<script src="{% static 'process/assets/js/jquery.min.js'%}"></script>
			<script src="{% static 'process/assets/js/skel.min.js'%}"></script>
			<script src="{% static 'process/assets/js/util.js'%}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'process/assets/js/main.js'%}"></script>

            </div>>
    </body>
</html>

templates/single.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}zhang_derek首页{% endblock %}


	{% block content %}




				<!-- Main -->
                    <li><button type="submit" onclick="window.location.href='{% url 'plans:create_process' plan.id %}'" >NEW</button></li>
					<div id="main">


						<!-- Post -->
                        {% for process in process_list %}
							<article class="post">
								<header>
									<div class="title">
										<h2><a href="{% url 'plans:process' plan.id %}">{{ process.process_name }}</a></h2>
{#										<p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>#}
									</div>
									<div class="meta">
										<time class="published" contenteditable="true" datetime="{{ process.start_time }}">{{ process.start_time }}</time>
                                        <time class="published" contenteditable="true" datetime="{{ process.end_time }}">{{ process.end_time }}</time>
{#										<a href="#" class="author"><span class="name">{{ plan.author }}</span><img src="{% static 'process/images/avatar.jpg'%}" alt="" /></a>#}
									</div>
								</header>
{#								<a href="#" class="image featured"><img src="{% static 'process/images/pic01.jpg'%}" alt="" /></a>#}

                                <p contenteditable="true">{{ process.content }}</p>
								<footer>

									<ul class="stats">

										<li><a href="#" class="icon fa-heart">28</a></li>
										<li><a href="#" class="icon fa-comment">128</a></li>

									</ul>
                                    <ul class="stats" style="margin-left:50%">


                                        <li><button type="submit" onclick="window.location.href='{% url 'plans:edit_plan' process.id %}'" >EDIT</button></li>
									</ul>

								</footer>
							</article>
                        {% endfor %}



			</div>



            </div>

    {% endblock %}

templates/task.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}zhang_derek首页{% endblock %}


	{% block content %}




				<!-- Main -->
                    <li><button type="submit" onclick="window.location.href='{% url 'plans:create_process' plan.id %}'" >NEW</button></li>
					<div id="main">


						<!-- Post -->
                        {% for task in task_list %}
							<article class="post">
                            <form action="/login/" method="post">
								<header>
									<div class="title">
										<h2><a href="#">{{ task.name }}</a></h2>
{#										<p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>#}
									</div>
									<div class="meta">
{#										<time class="published" contenteditable="true" datetime="{{ process.start_time }}">{{ process.start_time }}</time>#}
{#                                        <time class="published" contenteditable="true" datetime="{{ process.end_time }}">{{ process.end_time }}</time>#}
{#										<a href="#" class="author"><span class="name">{{ plan.author }}</span><img src="{% static 'process/images/avatar.jpg'%}" alt="" /></a>#}
									</div>
								</header>
{#								<a href="#" class="image featured"><img src="{% static 'process/images/pic01.jpg'%}" alt="" /></a>#}

                                <p contenteditable="true">{{ task.key_word }}</p>
                                <p contenteditable="true">{{ task.target_web }}</p>
                                <p contenteditable="true">{{ task.run_time }}</p>


									<ul class="stats">

										<li><a href="#" class="icon fa-heart">28</a></li>
										<li><a href="#" class="icon fa-comment">128</a></li>

									</ul>
                                    <ul class="stats" style="margin-left:50%">


                                        <li><button type="submit"  >保存</button></li>
									</ul>

								</form>
							</article>
                        {% endfor %}



			</div>



            </div>

    {% endblock %}